package com.example.audiotext.config;
import org.springframework.boot.context.properties.ConfigurationProperties;
import java.util.*;
@ConfigurationProperties(prefix="app")
public class AppProperties {
  private Storage storage=new Storage(); private Audio audio=new Audio(); private Vosk vosk=new Vosk(); private Processing processing=new Processing(); private Giga gigachat=new Giga();
  public Storage getStorage(){return storage;} public Audio getAudio(){return audio;} public Vosk getVosk(){return vosk;} public Processing getProcessing(){return processing;} public Giga getGigachat(){return gigachat;}
  public static class Storage { public String uploadDir,convertedDir,exportDir,databasePath; public String getUploadDir(){return uploadDir;} public void setUploadDir(String v){uploadDir=v;} public String getConvertedDir(){return convertedDir;} public void setConvertedDir(String v){convertedDir=v;} public String getExportDir(){return exportDir;} public void setExportDir(String v){exportDir=v;} public String getDatabasePath(){return databasePath;} public void setDatabasePath(String v){databasePath=v;} }
  public static class Audio { public String ffmpegPath="ffmpeg"; public List<String> allowedExtensions=new ArrayList<>(); public String getFfmpegPath(){return ffmpegPath;} public void setFfmpegPath(String v){ffmpegPath=v;} public List<String> getAllowedExtensions(){return allowedExtensions;} public void setAllowedExtensions(List<String> v){allowedExtensions=v;} }
  public static class Vosk { public boolean enabled=true; public String modelPath; public int sampleRate=16000; public boolean isEnabled(){return enabled;} public void setEnabled(boolean v){enabled=v;} public String getModelPath(){return modelPath;} public void setModelPath(String v){modelPath=v;} public int getSampleRate(){return sampleRate;} public void setSampleRate(int v){sampleRate=v;} }
  public static class Processing { public boolean useMockTranscriptionIfVoskUnavailable=true; public double lowConfidenceThreshold=0.6; public String fillerWordsPath,stopWordsPath,termDictionaryPath; public boolean isUseMockTranscriptionIfVoskUnavailable(){return useMockTranscriptionIfVoskUnavailable;} public void setUseMockTranscriptionIfVoskUnavailable(boolean v){useMockTranscriptionIfVoskUnavailable=v;} public double getLowConfidenceThreshold(){return lowConfidenceThreshold;} public void setLowConfidenceThreshold(double v){lowConfidenceThreshold=v;} public String getFillerWordsPath(){return fillerWordsPath;} public void setFillerWordsPath(String v){fillerWordsPath=v;} public String getStopWordsPath(){return stopWordsPath;} public void setStopWordsPath(String v){stopWordsPath=v;} public String getTermDictionaryPath(){return termDictionaryPath;} public void setTermDictionaryPath(String v){termDictionaryPath=v;} }
  public static class Giga { public boolean enabled=false; public String credentials="",scope="GIGACHAT_API_PERS",model="GigaChat"; public boolean verifySslCerts=false; public int timeoutSeconds=60; public boolean isEnabled(){return enabled;} public void setEnabled(boolean v){enabled=v;} public String getCredentials(){return credentials;} public void setCredentials(String v){credentials=v;} public String getScope(){return scope;} public void setScope(String v){scope=v;} public String getModel(){return model;} public void setModel(String v){model=v;} public boolean isVerifySslCerts(){return verifySslCerts;} public void setVerifySslCerts(boolean v){verifySslCerts=v;} public int getTimeoutSeconds(){return timeoutSeconds;} public void setTimeoutSeconds(int v){timeoutSeconds=v;} }
}
